#!/usr/bin/env python3
# Python version of the Makefile for dlut_uart_loader - complete validation workflow
# Auto-generated by hotc
# NOTE: This file is only generated if it doesn't exist. You can customize it.
#
# Does the same thing as the generated Makefile, without needing make:
#   python3 dlut_uart_loader.py [TARGET ...] [NAME=VALUE ...]
# Targets: all (default), generate, hw_sim, lint, sw_sim, compare, validate,
#          wave, clean.  NAME=VALUE overrides a variable, e.g. MAX_CYCLES=5000.

import os
import re
import subprocess
import sys

VARS = {
    "MODULE": "dlut_uart_loader",
    "SOURCE": "dlut_uart_loader.c",
    "SIMULATOR": "verilator",
    "VIEWER": "gtkwave",
    "C_PARSER": "../../bin/hotc",
    "SIM_BIN": "../../sim/bin/hotstate_sim",
    "COMPARE_SCRIPT": "../../scripts/compare_traces.py",
    "MAX_CYCLES": "1000",
}

# target: (prerequisites, recipe). A recipe line starting with "@" is run
# without being printed first, as in make.
TARGETS = {
    # Default target: run complete validation workflow
    "all": (["validate"], []),

    # Generate all artifacts using hotc
    "generate": ([], [
        '@echo "=== Generating artifacts from $(SOURCE) ==="',
        "$(C_PARSER) $(SOURCE) --all-hdl --microcode-hs",
        '@echo "Artifacts generated successfully!"',
    ]),

    # Compile and run Verilator hardware simulation
    "hw_sim": (["generate"], [
        '@echo "=== Running hardware simulation (Verilator) ==="',
        "$(SIMULATOR) --timing --cc -Wno-fatal --exe --trace --trace-structs --build -I. sim_main.cpp $(MODULE)_tb.v $(MODULE)_template.v ../../IP/hotstate.sv ../../IP/microcode.sv ../../IP/control.sv ../../IP/next_address.sv ../../IP/stack.sv ../../IP/switch.sv ../../IP/timer.sv ../../IP/variable.sv --top $(MODULE)_tb",
        '@echo "Running Verilator simulation..."',
        "./obj_dir/V$(MODULE)_tb",
        '@echo "Hardware simulation completed! Trace: hardware_trace.csv"',
    ]),

    # Lint-only check
    "lint": (["$(MODULE)_tb.v", "$(MODULE)_template.v"], [
        "$(SIMULATOR) --lint-only -Wall -Wno-WIDTH -Wno-UNUSED -Wno-DECLFILENAME -Wno-EOFNEWLINE -Wno-SYMRSVDWORD -Wno-PINMISSING -Wno-TIMESCALEMOD -Wno-LITENDIAN -Wno-SELRANGE -Wno-STMTDLY -Wno-PINCONNECTEMPTY -Wno-UNDRIVEN -Wno-BLKSEQ $(MODULE)_tb.v $(MODULE)_template.v ../../IP/hotstate.sv ../../IP/microcode.sv ../../IP/control.sv ../../IP/next_address.sv ../../IP/stack.sv ../../IP/switch.sv ../../IP/timer.sv ../../IP/variable.sv",
        '@echo "Verilog lint check successful!"',
    ]),

    # Run software simulator
    # Note: If you have a stimulus file (e.g. sweep.stim), add '-s sweep.stim' to the command below
    "sw_sim": (["generate"], [
        '@echo "=== Running software simulation ==="',
        "$(SIM_BIN) -b $(MODULE) --export $(MODULE)_sim.csv --max-cycles $(MAX_CYCLES)",
        '@echo "Software simulation completed! Trace: $(MODULE)_sim.csv"',
    ]),

    # Compare hardware and software traces
    "compare": (["hw_sim", "sw_sim"], [
        '@echo "=== Comparing traces ==="',
        "python3 $(COMPARE_SCRIPT) hardware_trace.csv $(MODULE)_sim.csv -v",
    ]),

    # Complete validation workflow
    "validate": (["compare"], [
        '@echo "=== Validation Complete ==="',
    ]),

    # View waveforms
    "wave": ([], [
        "$(VIEWER) sim_wf.vcd",
    ]),

    # Clean generated files
    "clean": ([], [
        "rm -rf obj_dir sim_wf.vcd hardware_trace.csv $(MODULE)_sim.csv",
        "rm -f $(MODULE)_tb.v $(MODULE)_template.v $(MODULE)_params.vh",
        "rm -f $(MODULE)_smdata.mem $(MODULE)_vardata.mem $(MODULE)_switchdata.mem $(MODULE)_timdata.mem",
        "rm -f $(MODULE)_symbols.toml sim_main.cpp verilator_sim.h",
    ]),
}


class BuildError(Exception):
    pass


def expand(text, overrides):
    """Replace $(NAME) the way make does: command line, then this file,
    then the environment, then empty."""
    def value(m):
        name = m.group(1)
        if name in overrides:
            return overrides[name]
        if name in VARS:
            return expand(VARS[name], overrides)
        return os.environ.get(name, "")
    return re.sub(r"\$\((\w+)\)", value, text)


def build(target, overrides, done):
    if target in done:
        return
    if target not in TARGETS:
        if os.path.exists(target):       # a file prerequisite that already exists
            done.add(target)
            return
        raise BuildError(f"No rule to make target '{target}'")
    prereqs, recipe = TARGETS[target]
    for p in prereqs:
        build(expand(p, overrides), overrides, done)
    for line in recipe:
        quiet = line.startswith("@")
        cmd = expand(line[1:] if quiet else line, overrides)
        if not quiet:
            print(cmd, flush=True)
        rc = subprocess.call(cmd, shell=True)
        if rc != 0:
            raise BuildError(f"[{target}] Error {rc}")
    done.add(target)


def main(argv):
    overrides, targets = {}, []
    for arg in argv:
        if arg in ("-h", "--help"):
            print(__doc__ or "", end="")
            print("usage: python3 %s [TARGET ...] [NAME=VALUE ...]" % os.path.basename(__file__))
            print("targets: " + ", ".join(t for t in TARGETS))
            return 0
        name, eq, val = arg.partition("=")
        if eq and re.fullmatch(r"\w+", name):
            overrides[name] = val
        else:
            targets.append(arg)
    # run from this file's directory, like make does from the Makefile's
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    done = set()
    try:
        for t in targets or ["all"]:
            build(t, overrides, done)
    except BuildError as e:
        print(f"{os.path.basename(__file__)}: *** {e}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
