[metadata]
generated_from = "step"
variable_count = 5

[state_variables]
"0" = { name = "tx_bit", type = "output", initial_value = 1, width = 1, is_unsigned = false }
"1" = { name = "tx_busy", type = "output", initial_value = 0, width = 1, is_unsigned = false }

[input_variables]
"0" = { name = "tx_start", type = "input", width = 1, start_bit = 0, referenced = true, compacted_start_bit = 0 }
"1" = { name = "tx_data", type = "input", width = 8, start_bit = 1, referenced = true, compacted_start_bit = 1 }

[switches]

[external_inputs]

[expressions]
